core: return a clear error message when database is not initialized
Currently, when the PostgreSQL database connected to Krenalis has not
been initialized, this error is shown to the user:

	error: ERROR: relation "metadata" does not exist (SQLSTATE 42P01)

which is unclear and doesn't indicate what needs to be done.

With this change, the error shown to the user in this scenario will
instead be:

	error: ERROR: relation "metadata" does not exist (SQLSTATE 42P01) (Krenalis's internal PostgreSQL may not be initialized. Try starting Krenalis with the -init-db-if-empty flag)