core: make database export working in case of duplicated users
This commit makes the database export working in cases when there are
duplicated users in Meergo (that are users with the same value for the
table key), if the database export connector uses the merge statement.

This is problematic because it currently returns errors like (this is an
example from the PostgreSQL connector):

	ERROR: MERGE command cannot affect row a second time (SQLSTATE 21000)