core/connectors/appwriter: fix data race and re-enable skipped test
Occasionally, tests failed with the following error:

--- FAIL: Test_Writer (0.02s)
    --- FAIL: Test_Writer/500/63/0.160000 (0.00s)
        writer_test.go:76: expected 500 IDs, got 497

The value 497 varied with each run. This issue was caused by concurrent
writes to the 'app.acks' slice without proper synchronization through a
lock.

This commit resolves the data race by adding the necessary
synchronization, and re-enables the test,

Fixes #1160