apis/datastore/warehouses/postgresql: improve info on error message
This commit adds information to the error message that occurs when
creating a new users table, which then contains the following error:

    ERROR: duplicate key value violates unique constraint "pg_type_typname_nsp_index"

This commit is therefore useful for resolving issue #984 and #1028.